### ISSUE TITLE
Doxygen warning in API reference

### ISSUE THREAD

**Issue by DoumanAsh** [fmtlib/fmtlib.github.io#1]
If you take a look at current API docs for 4.1 there is strange doxygen warning that got into description of [format](http://fmtlib.net/latest/api.html#_CPPv2N3fmt6formatE10CStringRef7ArgList)

```
Warning
doxygenfunction: Cannot find function “operator”“_format” in doxygen xml output for project “format” from directory: /private/tmp/fmt/build/doxyxml
```

**Comment by vitaut** [comment]
Fixed, thanks for reporting!
