### ISSUE TITLE
The godbolt.org example for argument lists doesn't compile

### ISSUE THREAD

**Issue by wscott** [fmtlib/fmtlib.github.io#15]
The latest api page on fmt.dev has a section "Argument Lists" which talks about using fmt::make_format_args.  It includes a link to compiler explorer, but that page has different code that doesn't compile anymore.

The godbolt example should be updated with the correct code and tied to the v9 fmt library so it doesn't break if this stuff changes again.  Here is a version I got working: https://godbolt.org/z/rz6o9jqbv

**Comment by vitaut** [comment]
Thanks for reporting. This has already been fixed in https://fmt.dev/dev/api.html#argument-lists but pinning to specific version is a good idea, we should do that.
