### ISSUE TITLE
Add example on how to format uint8_t into "0x00" with leading zeros

### ISSUE THREAD

**Issue by johnthagen** [fmtlib/fmtlib.github.io#2]
It's fairly common to want to format a `uint8_t` as hex with zero padding "0x00".

I stumbled over this a couple times until I finally found the solution:

`"{:#04x}"`

What's tricky about this is that the padding bytes count the `0x` in the string. If you don't realize this, you might think `{:#02x` is the logical format.

The examples in the [syntax](http://fmtlib.net/latest/syntax.html#format-examples) page don't need a padded `0`, so it's not as obvious you need this until your program prints a value of `0x0f` or less.

Do you think this is a good idea? If I am pointed at where this should be added, I'm also happy to submit a PR. I think this will help others in the future.

**Comment by vitaut** [comment]
> Do you think this is a good idea?

Sure.

> If I am pointed at where this should be added, I'm also happy to submit a PR.

A PR would be great. I think the Examples section is a good place to put it: https://github.com/fmtlib/fmt/blob/master/doc/syntax.rst#format-examples
